#theme: jekyll-theme-leap-day
title: "Tech Experience"
remote_theme: just-the-docs/just-the-docs
search_enabled: false
# Aux links for the upper right navigation
aux_links:
  "GitHub Repo":
    - "//github.com/manosenthill"
